# Generated by Django 5.2 on 2025-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=124),
        ),
    ]
